services:
  api:
    build:
      context: .
      dockerfile: basketball-tournament/Dockerfile
    container_name: basketball-api
    command: sh -c "yarn install && yarn run dev"  
    ports:
      - "3000:3000"  
    working_dir: /app  
    volumes:
      - ./:/app  
    environment:
      DATABASE_HOST: mysql  
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: basketball
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s  
      retries: 5 
      timeout: 20s   

  db:
    build:
      context: .
    container_name: Basketball_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678 
      MYSQL_DATABASE: basketball  
    volumes:
      - Basketball-mysql-data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  react-admin:
    build:
      context: .
      dockerfile: ra01-create-react-app/Dockerfile  
    container_name: react-admin
    ports:
      - "3006:3006" 
    depends_on:
      - api

volumes:
  Basketball-mysql-data:  

