services:
  api:
    build:
      context: ./basketball-tournament
      dockerfile: Dockerfile 
    container_name: basketball-api
    ports:
      - "8000:8000"
    volumes:
      - ./basketball-tournament:/home/node/app
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basketball-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: basketball
    volumes:
      - basketball-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  react-admin:
    build:
      context: ./ra01-create-react-app
      dockerfile: Dockerfile 
    container_name: react-admin
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  basketball-mysql-data:
